# ==============================================================================
# Docker Compose Configuration for the Watchers Monorepo
#
# This file defines the multi-container application setup for the "watchers" project.
# It is designed with best practices to ensure robustness, maintainability, and security.
#
# Key Features:
#   - Externalized Configuration: Uses a .env file for environment-specific variables
#     like ports, reducing hardcoded values.
#   - DRY (Don't Repeat Yourself): Leverages YAML extension fields (x-common-config)
#     to define a common configuration template for all services.
#   - Healthcheck-driven Startup: Uses `depends_on` with `service_healthy`
#     to ensure a reliable startup order based on service dependencies.
#   - Explicit Naming: Defines custom names for containers, networks, and volumes
#     for clarity and predictability.
#
# ==============================================================================
version: '3.8'

# ==============================================================================
# Extension Fields (for DRY principle)
#
# Defines a reusable configuration block that is applied to all services.
# This avoids repetition and makes the file easier to maintain.
# ==============================================================================
x-common-config: &common-config
  restart: unless-stopped
  volumes:
    # Mount a shared volume to cache Pip packages, speeding up builds.
    - pip-cache:/root/.cache/pip
    # Mount a shared log directory for all services.
    # The ':z' flag is crucial for Podman on SELinux-enabled systems (like Fedora, CentOS, RHEL).
    # It tells the container runtime to relabel the host volume content, allowing the container
    # to write to it without permission denied errors.
    - ./logs:/app/logs:z
  networks:
    - watchers_net
  environment:
    - PYTHONPATH=/app

# ==============================================================================
# Service Definitions
#
# Each block defines a microservice container.
# ==============================================================================
services:
  # ============================================================================
  # Core Services
  # ============================================================================

  ecu:
    <<: *common-config
    container_name: watchers-ecu
    build:
      context: ./ecu
      dockerfile: Dockerfile
    ports:
      # Port mapping is externalized to the .env file
      - "${ECU_PORT}:8000"
    environment:
      - PORT=8000
      - ECU_NUM_CAPAS=3
      - ECU_NUM_FILAS=4
      - ECU_NUM_COLUMNAS=5
      - ECU_SIM_INTERVAL=1.0
      - ECU_BETA_COUPLING=0.1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # ============================================================================
  # Control Plane
  # ============================================================================

  harmony_controller:
    <<: *common-config
    container_name: watchers-harmony-controller
    build:
      context: ./control
      dockerfile: Dockerfile
    ports:
      - "${HARMONY_CONTROLLER_PORT}:7000"
    environment:
      - PORT=7000
      - ECU_API_URL=http://ecu:8000/api/ecu
      - HC_KP=1.0
      - HC_KI=0.1
      - HC_KD=0.05
      - HC_SETPOINT_VECTOR=[1.0, 0.0]
      - HC_INTERVAL=1.0
      - HC_REQUESTS_TIMEOUT=2.0
      - HC_MAX_RETRIES=3
      - HC_BASE_RETRY_DELAY=0.5
    depends_on:
      ecu:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  agent_ai:
    <<: *common-config
    container_name: watchers-agent-ai
    build:
      context: ./agent_ai
      dockerfile: Dockerfile
    ports:
      - "${AGENT_AI_PORT}:9000"
    environment:
      - PORT=9000
      - HARMONY_CONTROLLER_URL=http://harmony_controller:7000
      - AGENT_AI_ECU_URL=http://ecu:8000
      - AGENT_AI_MALLA_URL=http://malla_watcher:5001
      - AA_INTERVAL=5.0
      - AA_REQUESTS_TIMEOUT=4.0
      - AA_MAX_RETRIES=3
      - AA_BASE_RETRY_DELAY=0.5
      - AA_INITIAL_STRATEGY=default
      - AA_INITIAL_SETPOINT_VECTOR=[1.0, 0.0]
      - AA_GLOBAL_REQ_PATH=/app/requirements.txt
    depends_on:
      harmony_controller:
        condition: service_healthy
      malla_watcher:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # ============================================================================
  # Watcher Tools
  # ============================================================================

  malla_watcher:
    <<: *common-config
    container_name: watchers-malla-watcher
    build:
      context: ./watchers/watchers_tools/malla_watcher
      dockerfile: Dockerfile
    ports:
      - "${MALLA_WATCHER_PORT}:5001"
    environment:
      - PORT=5001
      - MATRIZ_ECU_URL=http://ecu:8000
      - TORUS_NUM_CAPAS=3
      - TORUS_NUM_FILAS=4
      - TORUS_NUM_COLUMNAS=5
      - MW_INFLUENCE_THRESHOLD=5.0
      - MW_MAX_AMPLITUDE_NORM=20.0
      - MW_REQUESTS_TIMEOUT=2.0
      - MW_BASE_T=0.6
      - MW_BASE_E=0.1
      - MW_K_GAIN_T=0.1
      - MW_K_GAIN_E=0.05
      - MW_RADIUS=5.0
      - MW_HEIGHT_SEG=6
      - MW_CIRCUM_SEG=12
      - MW_HEX_SIZE=1.0
      - MW_PERIODIC_Z=True
      - MW_SIM_INTERVAL=0.5
    depends_on:
      ecu:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  watchers_wave:
    <<: *common-config
    container_name: watchers-watchers-wave
    build:
      context: ./watchers/watchers_tools/watchers_wave
      dockerfile: Dockerfile
    ports:
      - "${WATCHERS_WAVE_PORT}:5000"
    environment:
      - PORT=5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s

  watcher_focus:
    <<: *common-config
    container_name: watchers-watcher-focus
    build:
      context: ./watchers/watchers_tools/watcher_focus
      dockerfile: Dockerfile
    ports:
      - "${WATCHER_FOCUS_PORT}:6000"
    environment:
      - PORT=6000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6000/api/health"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s

# ==============================================================================
# Top-level Resources
#
# Defines named volumes and networks for the application.
# ==============================================================================
volumes:
  # Define a named volume for the Pip cache to persist between builds.
  pip-cache:
    name: watchers_pip_cache

networks:
  # Define a custom bridge network for inter-service communication.
  watchers_net:
    name: watchers_bridge_net
    driver: bridge
